houseprotect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('weatherchecker.urls')),
    path('admin/', admin.site.urls),
]

weatherchecker/urls.py
from django.urls import path

from . import views

app_name = 'weatherchecker'

urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.check, name='check')
]

weatherchecker/models.py
from django.db import models

# Create your models here.

weatherchecker/views.py
import csv, io, requests

from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from houseprotect import settings

# Create your views here.

def index(request):
	return render(request, 'weatherchecker/index.html', {})


def check(request):
	customer_csv = request.FILES['file']
	date = request.POST['date']
	results = []
	api_key = 'key=' + settings.WEATHER_API_KEY
	api_date_request = '&dt=' + date + '&q='
	request_api = "https://api.weatherapi.com/v1/history.json?" + api_key + api_date_request

	if not customer_csv.name.endswith('.csv'):
		messages.error(request, 'Please upload only csv file')
		return HttpResponseRedirect(reverse('weatherchecker:index'))


	data_set = customer_csv.read().decode('UTF-8')
	io_string = io.StringIO(data_set)
	next(io_string)

	for row in csv.reader(io_string, delimiter=','):
		weather = 'Cannot be determined'
		response = requests.get(request_api + row[6])

		if response.status_code == 200:
			condition = response.json()['forecast']['forecastday'][0]['day']['condition']
			weather = condition['text']

		customer = {
			'name':  row[1] + ' ' + row[2] + ' ' + row[3],
			'phone_number': row[8],
			'address': row[6],
			'weather': weather
		}
		results.append(customer)

	context = {
		'results': results,
		'date': date
	}
	return render(request, 'weatherchecker/results.html', context=context)

weatherchecker/templates/weatherchecker/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'weatherchecker/style.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<title>HouseProtect - WeatherChecker</title>
</head>
<body>

	<div class="container center">
		<h1>HouseProtect - WeatherChecker</h1>
		<h5>Please upload csv file and enter date</h5>
		<form action="{% url 'weatherchecker:check' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-group">
				<input type="file" name="file" class="file" required="true"><br>
				<input type="date" name="date" class="date" required="true"><br>
				<button type="submit" class="btn btn-primary submit">Check</button>
			</div>
		</form>

		{% if messages %}
		    {% for message in messages %}
		    	<div class="alert alert-danger">
		    		{{ message }}
		    	</div>
		    {% endfor %}
		{% endif %}
	</div>
</body>
</html>

weatherchecker/templates/weatherchecker/results.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'weatherchecker/style.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<title>Results</title>
</head>
<body>

	<div class="container results">
		<h1>Weather forecast on {{ date }}</h1>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Phone Number</th>
					<th>City Address</th>
					<th>Weather</th>
				</tr>
			</thead>
			<tbody>
				{% for result in results %}
				<tr>
					<th>{{ result.name }}</th>
					<th>{{ result.phone_number }}</th>
					<th>{{ result.address }}</th>
					<th>{{ result.weather }}</th>
				</tr>
				{% endfor %}
			</tbody>
		</table>

		<a href="{% url 'weatherchecker:index' %}" class="btn btn-primary">Upload Again?</a>
	</div>
</body>
</html>